version: "3.9"

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: notenwebanwendung
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:1234@db:5432/notenwebanwendung?sslmode=disable
